FROM farruq1988/php8.2:myapp

#RUN apt-get update \
#    && apt-get install -y nano iputils-ping telnet \
#    && apt-get clean \
#    && rm -rf /var/lib/apt/lists/*

###
# Install Node.js 14 and npm
#RUN apt-get update && apt-get install -y nodejs npm

# Verify Node.js and npm installation
#RUN node -v
#RUN npm -v

#docker network create library_network
