services:
  ########################### PHP ###########
  php1:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php1
    working_dir: /var/www/html/my_php_code
    volumes:
      - ./:/var/www/html/my_php_code
    networks:
      - my_php_code_network

  php2:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php2
    working_dir: /var/www/html/my_php_code
    volumes:
      - ./:/var/www/html/my_php_code
    networks:
      - my_php_code_network

  ########### Nginx Load Balancer ###########
  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "8002:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_php_code_network
    depends_on:
      - php1
      - php2

  ########################### PostgreSQL ###########
  postgres_primary:
    image: postgres:17.4
    container_name: pg_primary
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=my_php_code_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/pgdata_primary:/var/lib/postgresql/data
    networks:
      - my_php_code_network

  postgres_replica:
    image: postgres:17.4
    container_name: pg_replica
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=my_php_code_db
    volumes:
      - ./docker/pgdata_replica:/var/lib/postgresql/data
    networks:
      - my_php_code_network
    depends_on:
      - postgres_primary

  ########################### Redis ###########
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my_php_code_network

  ########################### Prometheus ###########
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - my_php_code_network

  ########################### Grafana ###########
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - my_php_code_network
    depends_on:
      - prometheus

  php1_exporter:
    image: hipages/php-fpm_exporter:2
    container_name: php1_exporter
    environment:
      - FPM_STATUS_URL=http://php1:9000/status
    networks:
      - my_php_code_network
    ports:
      - "9253:9253"
    depends_on:
      - php1

  php2_exporter:
    image: hipages/php-fpm_exporter:2
    container_name: php2_exporter
    environment:
      - FPM_STATUS_URL=http://php2:9000/status
    networks:
      - my_php_code_network
    ports:
      - "9254:9253"
    depends_on:
      - php2


networks:
  my_php_code_network:
    external: true
