version: '3'

services: #containers
  
  ########################### PHP ###########

  php_my_php_code:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: php_my_php_code
    volumes:
      - ./:/var/www/html/my_php_code
      - ./docker/xdebug/90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini
    working_dir: /var/www/html/my_php_code
    networks:
      - my_php_code_network
  
  ########### SERVER ########################
  #
  nginx_my_php_code:
    image: nginx:latest
    container_name: nginx_my_php_code
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www/html/my_php_code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_php_code_network
    expose:
      - 8002
  
  ############################## Data Base ###########
  postgresql_my_php_code:
    build:
      context: ./docker/db_conf
      dockerfile: Dockerfile
    container_name: postgresql_my_php_code
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_php_code_db
    restart: unless-stopped
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    tty: true
    networks:
      - my_php_code_network
    expose:
      - 5432

  ######################## COMPOSER #########

  composer_my_php_code:
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
    container_name: composer_my_php_code
    volumes:
      - ./:/var/www/html/my_php_code
      - ./docker/composer/cache:/root/.composer/cache
    working_dir: /var/www/html/my_php_code
    depends_on:
      - php_my_php_code
    networks:
      - my_php_code_network

  ################## ARTISAN ##############

  artisan_my_php_code:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: artisan_my_php_code
    volumes:
      - ./:/var/www/html/my_php_code
    depends_on:
      - postgresql_my_php_code
      - composer_my_php_code
    working_dir: /var/www/html/my_php_code
    entrypoint: ["php", "artisan"]
    command: ["queue:work"]
    restart: always
    networks:
      - my_php_code_network
  
  ############### redis ###########################

  redis_my_php_code:
    image: 'redis:alpine'
    container_name: redis_my_php_code
    ports:
      - "6390:6379"
    restart: unless-stopped
    networks:
      - my_php_code_network
    expose:
      - 6390
  
  ####################### node #######

  node:
    image: node:20
    container_name: npm
    volumes:
      - ./:/var/www/html/my_php_code
    working_dir: /var/www/html/my_php_code
    networks:
      - my_php_code_network
  
  ################# ES
  elasticsearch_my_php_code:
    image: 'elasticsearch:8.9.1'
    container_name: elasticsearch_my_php_code
    ports:
      - "9200:9200"
      - "9301:9301"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    networks:
      - my_php_code_network
    volumes:
      - ./docker/es_data:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9201
      - 9301
  ################### RabbitMQ
  rabbitmq_my_php_code:
    build:
      context: ./docker/rabbitmq
      dockerfile: Dockerfile
    hostname: "rabbitmq"
    container_name: rabbitmq_my_php_code
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_php_code_network
    volumes:
      - ./docker/rabbitmq/persistence/data/:/var/lib/rabbitmq/
      - ./docker/rabbitmq/persistence/log/:/var/log/rabbitmq
  
  ################## COMMAND to consumer rabbitmq msg ##############

  my_php_code_rabbitmq_consumer:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: my_php_code_rabbitmq_consumer
    volumes:
      - ./:/var/www/html/my_php_code
    depends_on:
      - postgresql_my_php_code
      - composer_my_php_code
    working_dir: /var/www/html/my_php_code
    entrypoint: ["php", "artisan"]
    command: ["temp_start_rabbitmq"]
    restart: always
    networks:
      - my_php_code_network


networks:
  my_php_code_network:
    external: true
