version: '3'

services: #containers
  
  ########################### PHP ###########

  php_my_php_code:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: php_my_php_code
    volumes:
      - ./:/var/www/html/my_php_code
      - ./docker/xdebug/90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini
    working_dir: /var/www/html/my_php_code
    networks:
      - my_php_code_network
  
  ########### SERVER ########################
  #
  nginx_my_php_code:
    image: nginx:latest
    container_name: nginx_my_php_code
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www/html/my_php_code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_php_code_network
    expose:
      - 8002
  
  ############################## Data Base ###########
  postgresql_my_php_code:
    build:
      context: ./docker/db_conf
      dockerfile: Dockerfile
    container_name: postgresql_my_php_code
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_php_code_db
    restart: unless-stopped
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    tty: true
    networks:
      - my_php_code_network
    expose:
      - 5432

  ######################## COMPOSER #########

  composer_my_php_code:
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
    container_name: composer_my_php_code
    volumes:
      - ./:/var/www/html/my_php_code
      - ./docker/composer/cache:/root/.composer/cache
    working_dir: /var/www/html/my_php_code
    depends_on:
      - php_my_php_code
    networks:
      - my_php_code_network


networks:
  my_php_code_network:
    external: true
